def print_image (case):
    if(case == "r_vs_p"):
        print "\n                                                                                            -/+:.\n                                                                                         `d/.`-oy-\n                        .:/++/:.                                                         `h/    `os`\n                   `:oss+:.``.:oh+`                                                 -/+/-  +y`    .y/      .oo++os`\n              -oossy/`      --`  oh                                               -h+.`.:ss/:h-     +y.   -h`    h.\n            `hs`oh-          .+++odsoss:               ``     ``  `..             +y`      .+sN+     `os- h-    /y\n            yo oy`-..`                `so              oN-   +N-`ydsyh`            -os+`      `/s.     `+sm`   :y\n           :m `N.`://++`               -m`              ym` :N/ `mh:`                 .os/`     `+`       .    s/\n           ss +h :so+/-.`         ``-:od-               `dh.No    -ohd-          -so+++++yms-                  :s\n           oy s+ //..-/++        .://::y+                .mNy   :h. `No          +s-       `/o`           ``   .d`\n           `ysyd``:oss:                `M`                -h`    +hyh+`           `:oso:`     .       `+- .y+` .my/\n             ..+h.                     /h`                                             -+oo/.          `+s+.-o`s/.h\n                -yo.           `-/++osyo`                                                  .+s+`      /oo/:+..h/`h-\n                  -sy+-`           .d/                                                        -os/.      .-.ss.-h-\n                     ./ooooo++++ooso-                                                            -/oo+++++hy:/so`\n                            `..``                                                                         `::.\n"   
    elif(case == "r_vs_s"):
        print "\n                    `:ossoo+ooss-                                                             `/++++++++/.`::.\n              `-:.+ys:`    `   .sy`                                                          oy-        ./yh:+y:\n            .ys/hd:         :++/:hy//-                                                      /s `/-         .y/`so\n           `d: yo              .-::.-+h+              :+    `+: `+ss:               ..::/+++hs+/`      /+oo: so s+\n           yo +h /oooo:                d/             .Ns   ym``Nh.-o`          `oso+:-..`               ./s: h/`m\n          `N. m:`:.`                  /d`              :N/ +N-  +dho-          `d-                    .oo+-:s`-d:h\n          -M .d  :/ossss.       `/+ooyN/                +NoN:   ` `/Ns         .d` `.-:::/++//-.         /s/  oy:`\n           d+.m`.sy+:`                 d/                sM+   -Ns:+N+          -os+/:/shs:`                 +y\n            oshy`  ./+                 h+                `/     `:+/.              .+oo-                   .s+\n               /h:                ```-ss                                          oo`       .:o+/-`     `/so`\n                `+h+.          .:/+sN+.                                          .d     `/os+:+so+/::+oso:\n                   -oys+:.``   ``-oh-                                            `h:.:oo+.        `..`\n                       .:/oooooo+:.                                                -:-\n"
    elif(case == "r_vs_r"):
        print "\n                            `..`                                                        `-/+++/-`\n                      `/ssso+//+oys`                                                  .yy/.```.:oss+- \n                `:+//ys:`    `.   -d/                                                -m.  .:.      .oyssoo.\n               sy:+d/         `/+++oNoo+-                                       `+soohy+o+:           /d--h+  \n              yo +h`              `..``.+h.           :+    `+: `+ss:          `d:                ``.-..m.`d:  \n             /d .N`.oooo+                /d           .Ns   ym``Nh.-o`         /d                -++//- oh :m  \n             h+ oy //-``                :d-            :N/ +N-  +dho-           +d/-.``         `-:/+oo`.m` N. \n             d+ h- --:+oss/       `-/oooyh`             +NoN:   ` `/Ns         `ho:://:`       .o+:-`-+. d.`N. \n             :d.h/ /sso:`                /d              sM+   -Ns:+N+         oh                 oss+. -N+h/ \n              .+od:   `:.                /d              `/     `:+/.          :d`                     :d:-`\n                 `sy.             ``.--:sh`                                     -ysoo+/:.            -hs` \n                   .sy/`         `.-:/No`                                          ho`           `:oyo` \n                      -oys+/--.``.-:oh/                                             +soo+//++oooso/` \n                          `-:/++++/-`                                                  ``...`` \n"
    elif(case == "p_vs_s"):
        print "\n                                 `\n                                   .oso+oy-\n                                 +y.    /h\n                 `/+o+/`       -y:    `so`                                                       `:/+++/:-`\n                 s/   .y+    `ss`    .h-.+so++os-                                              -y+-`   `.:+ohhoso`\n                 :y     h- `+y-     :mso+.     `m.                                            -h` .:         /y.-h:\n                  oo    +sos-     `sy:`      .+s/          /o`   `o: .+ss/                `.-:hy++-      .:+o:`h:`h-\n                   h.   -o`      .s.      .+s+`            .Ns   ym``Ny.-+`        -oooo++//:-.          -.`.+:`d..d\n                   m`            .     `/yy//++++.          :N+ oN-  /dhs:        y+`                   `/oo+-+`/h`m\n                  .h                  +s+//-.`  `d.          +NoN:   . `:Ns      -h       ``.----`      `. -os- /do-\n                 :yy   -s`  `       `/.      -+so/            sM+   -Ns:+N+       +ssoooosmms:.`           .`  -d`\n                `d.d -y+`.os:           `:+oo/.                /     `:+/`            .+so-                   /y.\n                `d`:h. /o+..+.       .+o+:`                                         :y/`       `-//-`      `+s:\n                 .h-.y+ .o+/.     `/s+`                                            `d      `/ssohy/-`  .:oso-\n                  `yo`:y+:.``.-/oso:                                               .d` `:oo+-     .:/++/-`\n                    -+o+s:////:.                                                    .o++:\n"
    elif(case == "p_vs_p"):
        print "\n                                                                                         ```\n                            `/o+o+-                                                    .oo++oo-\n                          `+s-   `d-                                                   os    .oo`\n           `---.`        :s:    .oo`  `                                           `..```/s.    -s/`      .:/++/.\n          `h:--:oo`    .s+`    :y-.:+o+o+:                                      -o+//+o+--y/     /s-    /s-```-d\n          `d`    +s  .+s-    `oh+o+:`   `so           `.     .`  ...`           d:     .:+ods`    .oo- `d`    o+\n           -y`    m-+o-     -sy/.     `-/s:           /m:   /m: sdosy.          -o+:.      -+s-     .+ooy    +s\n            /s    y/.      :+.     `-+o/.              oN- -N+ `hd/-.             `-+o:.     `/:      `:-   `d`\n            /s            `-     .+ys/::/:-`            yd:ms   `-/sd/         :++++/+ohs:`    `             h.\n            y:                 -oo+/:--...os            `dNy`  -h:.-Ns        `d/`  `..--/o-            `    s+\n          `+m-  `+:  .        -:`     .:+o+.             .y`    :sss/`         .:+o+:.     -`       .:` +o-  oys`\n          s/s+ +o-.:o+`          `-/+o/-.`                                        `.-/++/-          `:o+--+/`h.s:\n          +s`s+..++::/:       `/++:.`                                                  `.:o+-      `++///+ :y--h`\n           +s`/y:`/+:.`    `:oo-`                                                          ./o+-`    `.:.-s+`/s`\n            :s/.+s+:---:/+o+:`                                                               `.:+++////+ho:/s/`\n             `-++o/.---.``                                                                        ``````-:-.`\n"
    elif(case == "p_vs_r"):
        print "\n                           .:+/-\n                         -yo-`./d`\n                       `so`    /h`                                                         .:/++/:.\n        `so++oo.      /y.    `y+  -/+/-                                                 `+ho:.``.:+sso:`\n        .h    `h-   .y+     -h:/ss:.`.+h-                                               ho  `--      `/yssoo-\n         y/    -h -so`     +Ns+.      `y+                                          :ssosdo+++.          -ho`sh`\n          y:   `ms+`     .s/`      `+so-            `h+    oh``shhh/              os`                `..-`yo oy\n          /s    .       `+`     `/so.                :M/  +N: oN: .`             `m-               `++//:`.N` m:\n          s:                  -ymy+++++os-            oN--N+   /ydh:              -do:-``         `.-/+os: h+ ss\n         `d.   ``           `o/`       -s+             ymNs   ::  +M.             +y:://:.        ++/-..// +s yo\n        /ym. `+y. -+`       .     `:oso:`              `dy    /mysms             .M`                :sso:``dysy`\n        h./s`o-.+s+`          ./oo+-                    ``      ``               `h/                     .h+..\n        -h`/h..+:/oo/      `+s+.                                                  `oyso++/-`           .oy-\n         -h-.ss.-.      ./so-                                                        /d.           `-+ys-\n          `os/:yh+++++oo/-                                                            -osoo++++ooooo/.\n             .::`                                                                         ``..`\n"
    elif(case == "s_vs_s"):
        print "\n            `   ``..--..`                                                                     `.-::::-.\n         .+o+y+++/:::::/+o/                                                                 `+o/--...-:/+oh++o-\n        /y-:s/.       `.``+s                                                               `h: `-`       `:s/.so`\n       +o`+s.+:-.`     .//:d/...```                                                ```....-/d/+:`     `-:++`oo`+s\n      -h +s /:-::.        .-::////++++/`             `o-    /+ `/oo+.           .+o++//:::--.`        `---:+ oo y-\n      :y.m`-//++/-                   `:s:             sm.  :N/ oN/-/-          /s.                    :++//+-`m-y:\n       +om``/o/..-       `.---...```   -h             `hd`-No  .sys+.          h: ``..---::---`       .``+o:`.m+:\n         +y` `-`         `..-/yhyo+++ooo-              .dyms   -.`.ym`         .+oo+//oyhs:..``         `.  .y/\n          /s-                  .:++/.``                 .Nh`   sd++hy             `:+o/-`                 `/s-\n           `+o:.      .-::-.      `./s.                  -`     .--.             -s:.      `-/+/:.     `-+o:`\n             `:oo+:-.-:/oy++o+:.     :y                                          h-    `-/o+//so/::::/+o/.\n                ``.-::-.`    `-/++:.`+s                                          oo--/++-.`    ``.....`\n                                 `-:/:`                                           .--.`\n"
    elif(case == "s_vs_r"):
        print "\n                                                                                           ``\n          .::`./++++++++/`                                                             -ssoo+oosso:`\n        :y+:hy/.        -yo                                                          `ys.   `    `:sy+.:-`\n       os`/y.         -/` s/                                                      -//yh:/++:         :dh/sy.\n      +s os :oo+/      `/+sh+++/::..               `/.    ./` ./+/`             +h+-.::-.              oy :d`\n      m`/h :s/.               `..-:+oso`            sN.  `mh :Mo:oo            /d                :oooo/ h+ oy\n      h:d-`s:-+oo.                    -d`            hd` hd` .ddo:             `d/                  `.:`:m .N`\n      `:yo  /s/         .-//++/:::-.` `d.            `mysm.    `:hm.            /Nyoo+/`       .sssso/:  d. M-\n         y+                 `:shs/:/+so-              -NN-   sd-.oN.           /d                 `:+ys.`m.+d\n          +s.                   -oo+.                  :/     /os+.            +h                 +/.  `yhso\n           `os/`     `-/+o:.       `oo                                          ss-```                :h/\n              :oso+::/+os+:+so/`     d.                                          .+Ns+/:.          .+h+`\n                  `..`        .+oo:.:h`                                            -ho-``   ``.:+syo-\n                                  -:-                                                .:+oooooo/:.\n"
    elif(case == "s_vs_p"):
        print "\n                                                                                    `---`\n                                                                                   yo:-:oy-\n                  `-:/+++/:`                                                      `d:    `os`\n           `os+hho+:.`   `-+y-                                                -:-`  oy`    -h/       :oooos.\n          :h-.y/         :. `h-                                            `ss/::oso-:h.     oy.    so`   :y\n         -h`:h`:o+:.      -++yh:-.`                                        +y      ./oyN:     .ss. :y     h-\n         d..d`:+.`.-          .-://++oooo-         hh`   om.`ydhds          +s+.       :ss`     .ssy+    s+\n         m`h/`+-+oo/`                   `+y        .my  :M/ :Mo` `            `+so.      .o`      `/.   -h\n         -od/ -so- .`      `----.``       h-        -N+.No   .+hds`        /o+++/ohh/`     `            `m\n           `d-  `.           `.:smmsooooss+          /NNy       -M/       os    `.::/s+                  h.\n            .y/                   -os+.               sd`   -hhyds`        /ss+-      .:        `  `s:   hy/\n              :s+`      `-//-`       `/y:              `                      ./ooo:`           :so-`+y-`d`d.\n                -oso:.  `-/yhoss/`     `d`                                        `:os+`       .+-.+s/ .h:.d\n                   `-/++/:.     -+oo:` `d.                                            -ss:`     ./oo.`+y.-h-\n                                    :++o.                                               `/ss+:.```.-+y:`oy`\n                                                                                            `-:+++//yooo-\n"
    else:
        print "error"
                                                                                                                        



                                                                                                                        

                                                                                                                        
                                                                                                                        
                                                                                                                      

                                                                                                                        
                                                                                                                        

                                                                                                                        

                                                                                                                                                                                                                                                
                                                                                                                        
                                                                                                                        
